# <center> 第三部分 无监督学习</center>

有监督学习，无监督学。

无监督学习没有目标变量事先不存在。

# <center>第10章 利用K-均值聚类算法对为标注数据分组</center>

聚类是一种无监督学习。将相似的对象归到同一类。簇内的对象越相似聚类的效果越好。

自动分类，连类别体系都是自动构建的。

K-Means 发现k个不同的簇，每个簇的中心采用簇中所含值的均值计算而成。

聚类【无监督分类】。

In [ ]:
from numpy import *

数据加载
def loadDataSet(fileName):      #general function to parse tab -delimited floats
    dataMat = []                #assume last column is target value
    fr = open(fileName)
    for line in fr.readlines():
        curLine = line.strip().split('\t') 分隔空格tab
        fltLine = map(float,curLine) #map all elements to float()
        dataMat.append(fltLine)
    return dataMat

def distEclud(vecA, vecB):    欧式距离
    return sqrt(sum(power(vecA - vecB, 2))) #la.norm(vecA-vecB)


def randCent(dataSet, k):  随机创建聚类中心
    n = shape(dataSet)[1]
    centroids = mat(zeros((k,n)))  创建簇中心矩阵 #create centroid mat
    
    创建随机聚类中心，每一个维度上
    for j in range(n): 
        #create random cluster centers, within bounds边界 of each dimension
        找出每一维的最大值，最小值。
        minJ = min(dataSet[:,j]) 
        rangeJ = float(max(dataSet[:,j]) - minJ)  随机值的范围
        centroids[:,j] = mat(minJ + rangeJ * np.random.rand(k,1))
        有可能去0奥。那就是min
    return centroids

np.random.rand() 括号里买呢输入的是随机数组大小

创建一个给定类型的数组，将其填充在一个均匀分布的随机样本[0, 1)中

In [1]:
import numpy as np
print np.random.rand(3,2)

[[ 0.38282307  0.91455936]
 [ 0.72299274  0.97387075]
 [ 0.35787196  0.85234211]]


In [2]:
import kMeans

In [3]:
datMat = np.mat(kMeans.loadDataSet('testSet.txt'))

In [4]:
min(datMat[:,0])      #第一列最小值

matrix([[-5.379713]])

In [5]:
min(datMat[:,1])

matrix([[-4.232586]])

In [6]:
max(datMat[:,0])      #第一列最大值

matrix([[ 4.838138]])

In [7]:
max(datMat[:,1])

matrix([[ 5.1904]])

In [8]:
kMeans.randCent(datMat,2)

matrix([[ 2.80790667,  3.80749484],
        [-1.47616335,  2.7913515 ]])