In [3]:
from numpy import * 
import operator 
def createDataSet():
    group = array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
    labels = ['A','A','B','B']
    return group, labels
group,labels = createDataSet()
group.shape[0]

4L

### （1） shape 形状
 
 dataSetSize = dataSet.shape[0]  
 
 dataSet.shape[0] 第一行（维）数据的形状（即长度、大小）

### （2）tile:扩展数字

diffMat = tile(inX, (dataSetSize,1)) - dataSet __欧氏公式1 相减__

tile(inX, (A,B))  将在列的方向重复B次 行的方向重复A次

In [4]:
tile([0,0],(4,1))

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [5]:
tile([0,0],(4,1)) - group #做差

array([[-1. , -1.1],
       [-1. , -1. ],
       [ 0. ,  0. ],
       [ 0. , -0.1]])

（3）sqDiffMat = diffMat**2 __欧氏公式2 平方__

平方  给矩阵平方是给矩阵的每个项平方

 （4）sqDistances = sqDiffMat.sum(axis=1) __欧氏公式3 加和__
 
.sum(axis=0) 表是方向相加

.sum(axis=1) 表是行方向相加

（5）  distances = sqDistances**0.5 __欧氏公式4 开方（开根号）__

(6)sortedDistIndicies = distances.argsort()  

返回数组值从小到大的__索引值__

    sortedDistIndicies = distances.argsort()     
    classCount={}   
    #第二步：选择距离最小的k个点
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
   


### （3）.argsort()

In [9]:
import numpy as np
x = np.array([8, 112, 20,50])
indexl = x.argsort()
print indexl

[0 2 3 1]


In [10]:
for i in range(4):
    print indexl[i]

0
2
3
1


In [12]:
for i in range(4): 
    print [indexl[i]]  #索引排序

[0]
[2]
[3]
[1]


In [11]:
for i in range(4):
    print x[indexl[i]] #通过索引值排序后的数组

8
20
50
112


### (4).get()
字典的get方法

（7）dict.get(key, default=None)

classCount.get(voteIlabel,0) 是 classCount[voteIlabel]的值value

### （5）sorted()
（8）sortedClassCount = sorted(classCount.iteritems(), key=operator.itemgetter(1), reverse=True)


sorted(iterable[,cmp,[,key[,reverse=True]]])

iterable指定要排序的list或者iterable，不用多说

cmp为函数，指定排序时进行比较的函数

key为函数，指定取待排序元素的哪一项进行排序

reverse=True 升序排列；reverse=False 降序排列

### （6）.itemgetter(1)

函数 operator.itemgetter(1)  获取对象的第1个域的值  （从0开始编号）

In [15]:
a = [1,2,3] 
b=operator.itemgetter(1)

In [17]:
b(a)

2

### （7）.iteritems() 迭代器函数 往出取值

查看博客 http://blog.csdn.net/dongtingzhizi/article/details/12068205

## （8）.scatter()

ax.scatter(datingDataMat[:,0],datingDataMat[:,1],
         15.0*array(datingLabels),15.0*array(datingLabels))
         
利用变量datingLabels存储的类标签属性，在散点图上绘制色彩不等，尺寸不同的点 

.scatter(x,y,size,color)

        x = datingDataMat[:,0]
        y = datingDataMat[:,1]
        size = 15.0*array(datingLabels)
        color = 15.0*array(datingLabels)

# （9）.split()
split()就是将一个__字符串__分裂成__多个字符串__组成的__列表__

In [11]:
fileNameStr = "012_121.txt"
fileStr = fileNameStr.split('.')   
classNumStr = fileStr[0].split('_')
classNumStr1 = int(classNumStr[0])
print fileStr, '\n'*2 ,classNumStr, '\n'*2 ,classNumStr1

['012_121', 'txt'] 

['012', '121'] 

12


In [6]:
 u = "www.doiido.com.cn"

In [7]:
print u.split('.')

['www', 'doiido', 'com', 'cn']


# (10) extend() 和 append()

也就是说a.append(b)是往后加一个list  但是 a.extend(b) 平行排列 是将a和b的所有元素组合成一个列表

In [1]:
a=[1,2,3]
b=[4,5,6]
a.append(b)
a

[1, 2, 3, [4, 5, 6]]

In [2]:
a=[1,2,3]
b=[4,5,6]
a.extend(b)
a

[1, 2, 3, 4, 5, 6]

# （11） set()

In [3]:
a = [1,2,3,4,2,3,1,2,3,1,4]
set(a)

{1, 2, 3, 4}

# （12） 绘图过程中出现中文错误

In [ ]:
产生中文乱码的原因就是字体的默认设置中并没有中文字体，所以我们只要手动添加中文字体的名称就可以了

from pylab import *  
mpl.rcParams['font.sans-serif'] = ['SimHei'] 